pipeline {
    agent { label 'JDK-17'}
    stages{

        stage('vcs') {
            steps{
                git branch: 'main',
                       url: 'https://github.com/divyakothuru311/terraform-tasks.git'
            }
        }
        stage('create vpc via terraform') {
            steps{
                sh 'terraform init'
                sh 'terraform validate'
                sh 'terraform apply --auto-approve'
            }
        }
    }
}