pipeline {
    agent { label 'JDK-17'}
    stages{
        stage('create vpc via terraform') {
            steps{
                sh 'terraform init'
                sh 'terraform validate'
                sh 'terraform apply --auto-approve'
            }
        }
    }
}